🎉 add: an easy way to see if there are leaks or errors

diff --git a/module_9/ex00/Makefile b/module_9/ex00/Makefile
--- a/module_9/ex00/Makefile
+++ b/module_9/ex00/Makefile
@@ -57,6 +57,7 @@ CC := c++
 C_FLAGS := -Wall -Wextra -Werror -std=c++98 -g3
 FSANITIZE = -fsanitize=address
 VALGRIND_FLAGS = --leak-check=full --show-leak-kinds=all --trace-children=yes --track-origins=yes
+VALGRIND_FILE = valgrind_output.txt
 
 RM := rm -rf
 USER := $(shell whoami)
@@ -100,25 +101,38 @@ re: fclean
 debug: C_FLAGS += $(FSANITIZE)
 debug: fclean $(NAME)
 
+# Define a function to check for errors or leaks in Valgrind output
+define check_valgrind_output
+	@if grep -q "ERROR SUMMARY: [1-9]" $1 || grep -q "LEAK SUMMARY: [1-9]" $1; then \
+		cat $1; \
+		echo -e "$(BG_RED) LEAK: $(RESET)$(FG_RED)Valgrind found errors or leaks.$(RESET)"; \
+	else \
+		echo -e "$(BG_GREEN) NO LEAK:$(RESET) $(FG_GREEN)Valgrind found no errors or leaks.$(RESET)"; \
+	fi
+	@rm -f $1
+endef
+
 valgrind: VALGRIND = valgrind $(VALGRIND_FLAGS)
+valgrind: VALGRIND_SUFFIX = > $(VALGRIND_FILE) 2>&1
 valgrind: run
+	$(call check_valgrind_output, $(VALGRIND_FILE))
 
 run: all
 	@echo -e "\n\e[;1;33m* \e[21m\e[34mTesting with no file\e[0m\n"
-	@$(VALGRIND) ./$(NAME) || true
+	@$(VALGRIND) ./$(NAME) $(VALGRIND_SUFFIX) || true
 	@echo -e "\n\e[1;33m* \e[21m\e[34mTesting with too many arguments\e[0m\n"
-	@$(VALGRIND) ./$(NAME) input.txt input.txt || true
+	@$(VALGRIND) ./$(NAME) input.txt input.txt $(VALGRIND_SUFFIX) || true
 	@echo -e "\n\e[1;33m* \e[21m\e[34mTesting with an empty string\e[0m\n"
-	@$(VALGRIND) ./$(NAME) "" || true
+	@$(VALGRIND) ./$(NAME) "" $(VALGRIND_SUFFIX) || true
 	@echo -e "\n\e[1;33m* \e[21m\e[34mTesting with a string\e[0m\n"
-	@$(VALGRIND) ./$(NAME) "Hello World" || true
+	@$(VALGRIND) ./$(NAME) "Hello World" $(VALGRIND_SUFFIX) || true
 	@echo -e "\n\e[1;33m* \e[21m\e[34mTesting with missing file\e[0m\n"
-	@$(VALGRIND) ./$(NAME) nope.txt || true
+	@$(VALGRIND) ./$(NAME) nope.txt $(VALGRIND_SUFFIX) || true
 	@echo -e "\n\e[1;33m* \e[21m\e[34mTesting with empty file\e[0m\n"
 	@touch empty.txt
-	@$(VALGRIND) ./$(NAME) empty.txt || true
+	@$(VALGRIND) ./$(NAME) empty.txt $(VALGRIND_SUFFIX) || true
 	@echo -e "\n\e[1;33m* \e[21m\e[34mTesting with input.txt file\e[0m\n"
-	@$(VALGRIND) ./$(NAME) input.txt || true
+	@$(VALGRIND) ./$(NAME) input.txt $(VALGRIND_SUFFIX) || true
 
 
 .PHONY: all clean fclean re debug valgrind run
